[all:vars]
ansible_user=<USER>
ansible_password=<USER_PASSWORD>
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[soc]
soc-server ansible_host=<IP_ADDRESS>

[debian]
debian-hostname ansible_host=<IP_ADDRESS>

[fedora]
fedora-hostname ansible_host=<IP_ADDRESS>

[centos]
centos-hostname ansible_host=<IP_ADDRESS>